export const OFFICERS_MOCK_DATA = [
    {
      serialNo:1,
      name:'Sri P Sreenivasulu, I.A.S',
      designation:'Commissioner',
      mobile:9849908385,
      email:'mc.guntur@cdma.gov.in',
      image:'/assets/comissioner.jpg'
    },
    {
      serialNo:2,
      name:'Sri C Obulesu',
      designation:'Additional Commissioner',
      mobile:9849908396,
      email:'ac.gurntucorporation.gmail.com',
      image:'/assets/officer-4.jpg',
    },
    {
      serialNo:3,
      name:'Sri D Srinivasarao',
      designation:'Deputy Commisisioner-1',
      mobile:9849908364,
      email:'dc1.gunturcorporation@gmail.com',
      image:'/assets/officer-1.jpg'
    },
    {
      serialNo:4,
      name:'Sri Ch Srinivas',
      designation:'Deputy Commisisioner-2',
      mobile:9704600939,
      email:'dc2.gunturcorporation.gmail.com',
      image:'/assets/officer-2.jpg'
    },
    {
      serialNo:5,
      name:'Sri T Venkata Krishnaiah',
      designation:'Deputy Commisisioner-3',
      mobile:9963995326,
      email:'dc3.gunturcorporation.gmail.com',
      image:'/assets/officer-3.jpg',
    },
    {
      serialNo:6,
      name:'Sri. Sundar Rami Reddy',
      designation:'Superintending Engineer I/c',
      mobile:9849908400,
      email:'sundarramireddy@gmcguntur.com',
    },
    {
      serialNo:7,
      name:'Sri Jinka Nagendra Kumar',
      designation:'Examiner Of Accounts',
      mobile:9849908373,
      email:'acct.gunturcorporation.gamil.com',
      image:'/assets/officer-5.jpg',
    },
    {
      serialNo:8,
      name:'Sri. D Rambabu',
      designation:'City Planner',
      mobile:9849908390,
      email:'cp.gunturcorporation.gmail.com',
      image:'/assets/officer-7.jpg',
    },
    {
      serialNo:9,
      name:'Dr Sobha Rani',
      designation:'EChief Medical of Health',
      mobile:7799222882,
      email:'cmho.gunturcorporation@gmail.com',
      image:'/assets/officer-6.jpg',
    },
    {
      serialNo:10,
      name:'Dr. M Ravi Babu',
      designation:'Municipal Health Officer',
      mobile:8919797379,
      email:'mho.gunturcorporation@gmail.com',
      image:'/assets/officer-8.jpg',
    },
    {
      serialNo:11,
      name:'N Madhusudhana Rao',
      designation:'Biologist',
      mobile:9160233356,
      email:'madhusudhanarao@gmcguntur.com',
    },
  ]